### ISSUE TITLE
Support for AVIF format

### ISSUE THREAD

**Issue by mystrdat** [juliomrqz/nuxt-optimized-images#233]
https://reachlightspeed.com/blog/using-the-new-high-performance-avif-image-format-on-the-web-today/

**Comment by juliomrqz** [comment]
Please, provide more context for your request, follow the issue templates.

**Comment by mystrdat** [comment]
My apologies, updated the post with context. @juliomrqz

**Comment by ymilhahn** [comment]
FYI sharp is now supporting AVIF. :)

https://sharp.pixelplumbing.com/changelog#v027---avif
https://github.com/lovell/sharp/issues/2289
