### ISSUE TITLE
Not compiling with nuxt

### ISSUE THREAD

**Issue by StephenMarkToms** [juliomrqz/nuxt-optimized-images#237]
**Describe the bug**

Developed a site using a macbook 2018 and love the library and optimizations it delivered. Unfortunately, my laptop died and needed to get another one. Now just cloning the repo and then running I get the following error: 

 WARN  Compiled with 1 warnings                                                                                                   friendly-errors 00:48:21

 WARN  in ./assets/img/why-professional-website-design-will-help-your-business-make-money.jpg                                     friendly-errors 00:48:21

Module parse failed: Unexpected character '�' (1:0)                                                                               friendly-errors 00:48:21
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
                                                                                                                                  friendly-errors 00:48:21
 @ . sync ^\.\/assets.*$
 @ ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/news/_news.vue?vue&type=template&id=661377af&
 @ ./pages/news/_news.vue?vue&type=template&id=661377af&
 @ ./pages/news/_news.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
                                                                                                                                  friendly-errors 00:48:21

 ERROR  Failed to compile with 1 errors                                                                                           friendly-errors 00:48:21

 ERROR  in ./assets/img/video-thumbnail.jpg?webp                                                                                  friendly-errors 00:48:21

Module parse failed: Unexpected character '�' (1:0)                                                                               friendly-errors 00:48:21
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
                                                                                                                                  friendly-errors 00:48:21
 @ ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./components/home/Header.vue?vue&type=template&id=3c3e0572& 87:30-78
 @ ./components/home/Header.vue?vue&type=template&id=3c3e0572&
 @ ./components/home/Header.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&
 @ ./pages/index.vue?vue&type=script&lang=js&
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js

**To Reproduce**
1. clone repo
2. npm install
3. npm run dev

**Additional context**
The repo is built using a CI/CD pipeline with netlify. If I push a commit to see if it builds on the production side it works fine.

**Comment by juliomrqz** [comment]
@StephenMarkToms Can you provide a live example? Maybe using CodeSandbox. Thanks.

**Comment by devzakir** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> Developed a site using a macbook 2018 and love the library and optimizations it delivered. Unfortunately, my laptop died and needed to get another one. Now just cloning the repo and then running I get the following error:
> 
> WARN Compiled with 1 warnings friendly-errors 00:48:21
> 
> WARN in ./assets/img/why-professional-website-design-will-help-your-business-make-money.jpg friendly-errors 00:48:21
> 
> Module parse failed: Unexpected character '�' (1:0) friendly-errors 00:48:21
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> (Source code omitted for this binary file)
> friendly-errors 00:48:21
> @ . sync ^./assets.*$
> @ ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/news/_news.vue?vue&type=template&id=661377af&
> @ ./pages/news/_news.vue?vue&type=template&id=661377af&
> @ ./pages/news/_news.vue
> @ ./.nuxt/router.js
> @ ./.nuxt/index.js
> @ ./.nuxt/client.js
> @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
> friendly-errors 00:48:21
> 
> ERROR Failed to compile with 1 errors friendly-errors 00:48:21
> 
> ERROR in ./assets/img/video-thumbnail.jpg?webp friendly-errors 00:48:21
> 
> Module parse failed: Unexpected character '�' (1:0) friendly-errors 00:48:21
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> (Source code omitted for this binary file)
> friendly-errors 00:48:21
> @ ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./components/home/Header.vue?vue&type=template&id=3c3e0572& 87:30-78
> @ ./components/home/Header.vue?vue&type=template&id=3c3e0572&
> @ ./components/home/Header.vue
> @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&
> @ ./pages/index.vue?vue&type=script&lang=js&
> @ ./pages/index.vue
> @ ./.nuxt/router.js
> @ ./.nuxt/index.js
> @ ./.nuxt/client.js
> @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. clone repo
> 2. npm install
> 3. npm run dev
> 4. See error
> 
> **Additional context**
> The repo is built using a CI/CD pipeline with netlify. If I push a commit to see if it builds on the production side it works fine.

I have the same problem
![image](https://user-images.githubusercontent.com/33604077/111867943-6f997500-89a1-11eb-9983-4cb9e07ed28a.png)

**Comment by StephenMarkToms** [comment]
Can we re-open this issue, seeing that others are having a similar problem?

**Comment by ZS-Andisch** [comment]
Same problem here with .svg . I do not want to handle svg so i removed it from handleImages: ['jpeg', 'png'] but than i got this error.

**Comment by archieDeveloper** [comment]
And me!

**Comment by yaeru** [comment]
Me too

**Comment by Liaguta** [comment]
I had the same error. After removing the imagemin-svgo package, the error disappeared. But if I set optimizeImagesInDev to true in the config the error reappears.
![Screenshot_1](https://user-images.githubusercontent.com/84125174/159162466-bb8a411b-f18b-4ed0-88f2-e4653bf3366d.png)
![Screenshot_8](https://user-images.githubusercontent.com/84125174/159162467-a62e3c95-824c-42de-b272-1ed44d60f3c2.png)
