### ISSUE TITLE
Example to use responsive-loader?

### ISSUE THREAD

**Issue by tonywei92** [juliomrqz/nuxt-optimized-images#260]
![image](https://user-images.githubusercontent.com/20355806/95850862-a4aef500-0d7b-11eb-91f8-681bc6dd01ae.png)
How do I implement this?
because if I just following the docs, the `.src` and `.srcSet` is empty

```
  optimizedImages: {
    optimizeImages: true,
    mozjpeg: {
      quality: 85,
    },
    pngquant: {
      quality: [0.6, 0.8]
    },
    responsive: {
      // If you want to enable sharp support:
      adapter: require('responsive-loader/sharp'),
      sizes: [640, 960, 1200],
    }
  },
```

and that's weird the `responsive` property not included in default config: https://github.com/juliomrqz/nuxt-optimized-images/blob/develop/lib/config.js

Thank you

**Comment by juliomrqz** [comment]
You can take a look at the Examples https://github.com/juliomrqz/nuxt-optimized-images/blob/develop/example/pages/responsive.vue
