### ISSUE TITLE
Documentation recommends to install as a devDependency yet it should be in dependencies?

### ISSUE THREAD

**Issue by gkatsanos** [juliomrqz/nuxt-optimized-images#285]
**Describe the bug**
When `NODE_ENV=production yarn build` is used , build fails if this package is in devDependencies. 

Change recommendation to remove --dev flag from the add/install command.

**Comment by juliomrqz** [comment]
Hello @gkatsanos. `nuxt-optimized-images` is used only on the building process; it's not required when the website is accessed on production. That's why it's a dev dependency.
