### ISSUE TITLE
Confused where to ask questions

### ISSUE THREAD

**Issue by dertrockx** [juliomrqz/nuxt-optimized-images#290]
I'm trying to access [https://spectrum.chat/bazzite/open-source]( https://spectrum.chat/bazzite/open-source), but it seems that the spectrum community is not active anymore. 

Is it moved elsewhere or brought back here? Thanks.

**Comment by juliomrqz** [comment]
Hello @dertrockx. Sorry for the confusion. Starting today the Questions can be placed in the **Discussions** section of the repository https://github.com/juliomrqz/nuxt-optimized-images/discussions.
